apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: codis-proxy
        service: codis-proxy
    spec:
      containers:
        - name: codis-proxy
          image: niexiaohu/codis-proxy
          env:
            - name: ZOOKEEPER
              value: "10.3.0.216"
            - name: PRODUCT
              value: "bfdcodis"
            - name: DASHBOARD
              value: "10.3.0.124"
            - name: PROXYID
              value: "proxy_01"
            - name: CPU
              value: "2"
          ports:
            - containerPort: 11000
            - containerPort: 19000
          volumeMounts:
            - mountPath: /opt/codis/logs
              name: log
      volumes:
        - emptyDir: {}
          name: log